### PR TITLE
11.X build update

### PR DESCRIPTION
**Pull request by sean-**
Update the build process significantly and introduce JSON5 as a template language.  Move all of this work under `11.0/`.  I need to manually resolve the conflicts in some of the older top-level `.json` files.  Ideally these files go away in favor of the style seen in `11.0/`.

### CODE REVIEW

**Comment by sean-** [comment]
@brd For a few reasons I didn't test the top-level changes to the `.json` files after merging the conflicts.  If the `11.0/` style looks good to you, I'm going to blow away the top-level directory bits in favor of what's present under `11.0/` and will add UFS.  Having comments for the `boot_commands` is mandatory for maintenance, imo.  LMK what you think.  Feel free to clobber any of the work in the top-level directory.  I made a bunch of changes a while back and never pushed them up, but don't know what each line was in the `boot_commands`.  I commented up the `.json5` version so we shouldn't have this problem in the future:

https://github.com/sean-/packer-freebsd/blob/master/11.0/amd64-20170510-r318134-zfs.json5#L34-L165

I also updated the `Vagrantfile` to have NFS shared folders support out of the box, too (provided you apply the patch to Vagrant).  LMK.

CC @swills in case he has some opinions or feedback

**Comment by sean-** [comment]
Kk, 11.0, 11.1, and 12.0 have all been added to this PR and it should be good to merge pending my comments re: the json merge conflicts/resolution in the top-level directory .json files. If this looks good and ppl are interested, I'll clean up the older scripts in the root directory and do some code reuse work to minimize the duplication of some resources.

**Comment by brd** [comment]
Ohh, yeah I like this a lot better... thanks Sean!

**Comment by sean-** [comment]
KK.  I'm going to run through this one more time to get UFS builds again and then I'm going to merge this.  This PR will include a removal of the UFS and scripts from the root directory and updated docs.

**Pull request merged**
